<?xml version="1.0" encoding="UTF-8"?>
<tileset version="1.5" tiledversion="1.7.2" name="dungeon-tileset" tilewidth="16" tileheight="16" tilecount="110" columns="10" objectalignment="topleft">
 <image source="../../game/art/tilesets/dungeon.png" width="160" height="176"/>
 <tile id="0" type="wall"/>
 <tile id="1" type="wall"/>
 <tile id="2" type="wall"/>
 <tile id="3" type="wall"/>
 <tile id="4" type="wall"/>
 <tile id="5" type="wall"/>
 <tile id="6" type="floor"/>
 <tile id="7" type="floor"/>
 <tile id="8" type="floor"/>
 <tile id="9" type="floor"/>
 <tile id="10" type="wall"/>
 <tile id="11" type="floor"/>
 <tile id="12" type="floor"/>
 <tile id="13" type="floor"/>
 <tile id="14" type="floor"/>
 <tile id="15" type="wall"/>
 <tile id="16" type="floor"/>
 <tile id="17" type="floor"/>
 <tile id="18" type="floor"/>
 <tile id="19" type="floor"/>
 <tile id="20" type="wall"/>
 <tile id="21" type="floor"/>
 <tile id="22" type="floor"/>
 <tile id="23" type="floor"/>
 <tile id="24" type="floor"/>
 <tile id="25" type="wall"/>
 <tile id="26" type="floor"/>
 <tile id="27" type="floor"/>
 <tile id="28" type="floor"/>
 <tile id="29" type="floor"/>
 <tile id="30" type="wall"/>
 <tile id="31" type="floor"/>
 <tile id="32" type="floor"/>
 <tile id="33" type="floor"/>
 <tile id="34" type="floor"/>
 <tile id="35" type="wall"/>
 <tile id="36" type="wall"/>
 <tile id="37" type="wall"/>
 <tile id="40" type="wall"/>
 <tile id="41" type="wall"/>
 <tile id="42" type="wall"/>
 <tile id="43" type="wall"/>
 <tile id="44" type="wall"/>
 <tile id="45" type="wall"/>
 <tile id="50" type="wall"/>
 <tile id="51" type="wall"/>
 <tile id="52" type="wall"/>
 <tile id="53" type="wall"/>
 <tile id="54" type="wall"/>
 <tile id="55" type="wall"/>
 <tile id="60" type="floor"/>
 <tile id="61" type="floor"/>
 <tile id="62" type="floor"/>
 <tile id="63" type="floor"/>
 <tile id="70" type="floor"/>
 <tile id="71" type="floor"/>
 <tile id="72" type="floor"/>
 <tile id="73" type="floor"/>
 <tile id="78" type="pit"/>
 <tile id="100" type="pit"/>
</tileset>
